name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@a0837df06d10de2cae8a99319e8e101a6cbe9083 # v8.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
